---
#https://aur.archlinux.org/packages/visual-studio-code-bin

- name: Install Microsoft Visual Studio Code from AUR
  kewlfft.aur.aur:
    use: yay
    name:
      - visual-studio-code-bin
  when: archlinux_flavor == "Visual Studio Code"
